name: Deploy to Zume (SFTP password)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Workaround: ensure SSH config exists so the deploy action doesn't fail
      - name: Prep SSH config
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          chmod 600 ~/.ssh/config
          printf "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config

      # (optional) make sure the target folder exists
      - name: Ensure remote dir exists
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SFTP_PASS }}" sftp -o StrictHostKeyChecking=no ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }} << 'EOF'
          mkdir wilsonrlewis
          mkdir wilsonrlewis/zombie_game
          EOF

      - name: Upload via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST }}
          remote-user: ${{ secrets.SFTP_USER }}
          remote-password: ${{ secrets.SFTP_PASS }}   # or ssh-private-key: ${{ secrets.SFTP_KEY }}
          remote-path: wilsonrlewis/zombie_game       # relative to your SFTP home
          local-path: .                                # index.html is at repo root
          sync: full                                   # switch to 'delta' after first success
          debug: true
          # remote-port: 22                            # set if your SFTP uses a custom port
