name: Deploy to Zume (SFTP password)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show local files
        run: |
          pwd
          ls -la

      - name: Debug SFTP listing
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SFTP_PASS }}" sftp -o StrictHostKeyChecking=no ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }} << 'EOF'
          pwd
          ls -la
          ls -la wilsonrlewis
          ls -la wilsonrlewis/zombie_game
          EOF

      - name: Upload via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST }}
          remote-user: ${{ secrets.SFTP_USER }}
          remote-password: ${{ secrets.SFTP_PASS }}
          remote-path: wilsonrlewis/zombie_game   # your target folder
          local-path: .                           # change if your files live elsewhere
          sync: full
          debug: true
