name: Deploy to Zume (SFTP password, debug)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show local files
        run: |
          pwd
          ls -la

      - name: Network & DNS checks
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          PORT: 22        # change if your host uses a custom SFTP port
        run: |
          echo "Resolving $HOST ..."
          getent hosts "$HOST" || true
          echo "Testing TCP connectivity to $HOST:$PORT ..."
          sudo apt-get update && sudo apt-get install -y netcat-openbsd
          nc -vz "$HOST" "$PORT" || true

      - name: SFTP verbose login (non-fatal)
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USER: ${{ secrets.SFTP_USER }}
          PASS: ${{ secrets.SFTP_PASS }}
          PORT: 22        # change if needed
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          echo "Trying SFTP with -vvv for detailed errors..."
          sshpass -p "$PASS" sftp -vvv -o StrictHostKeyChecking=no -P "$PORT" "$USER@$HOST" << 'EOF'
          pwd
          ls -la
          ls -la wilsonrlewis
          ls -la wilsonrlewis/zombie_game
          EOF
        continue-on-error: true

      - name: Upload via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST }}
          remote-user: ${{ secrets.SFTP_USER }}
          remote-password: ${{ secrets.SFTP_PASS }}
          remote-path: wilsonrlewis/zombie_game   # <- your target folder
          local-path: .                           # change if your files live elsewhere
          sync: full
          debug: true
          # remote-port: 22                       # uncomment & set if non-standard
