name: Deploy to Zume (SFTP)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build upload folder (exclude git/CI files)
      - name: Prepare upload dir
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          rsync -av \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='.gitattributes' \
            --exclude='.gitignore' \
            ./ upload/
          echo "Uploading these files:" && ls -la upload/

      # Deploy just the upload/ contents
      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}        # or ssh_private_key: ${{ secrets.SFTP_KEY }}
          local_path: upload
          remote_path: wilsonrlewis/zombie_game     # adjust if needed
          sftp_only: true
          delete_remote_files: false
          # port: 22                                  # set if your SFTP port isn't 22
