name: Deploy to Zume (rsync over SSH)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install needed tools once
      - name: Install rsync & sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      # Make sure secrets exist (won't print values)
      - name: Validate secrets
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USER: ${{ secrets.SFTP_USER }}
          PASS: ${{ secrets.SFTP_PASS }}
        run: |
          [ -n "$HOST" ] || (echo "::error ::SFTP_HOST missing" && exit 1)
          [ -n "$USER" ] || (echo "::error ::SFTP_USER missing" && exit 1)
          [ -n "$PASS" ] || (echo "::error ::SFTP_PASS missing" && exit 1)

      # Create the remote directory if it doesn't exist
      - name: Ensure remote dir exists
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USER: ${{ secrets.SFTP_USER }}
          PASS: ${{ secrets.SFTP_PASS }}
        run: |
          sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no -p 22 "$USER@$HOST" \
            "mkdir -p 'wilsonrlewis/zombie_game'"

      # Deploy the repo contents (excluding git/CI files) INTO that folder
      - name: Deploy with rsync (password)
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USER: ${{ secrets.SFTP_USER }}
          PASS: ${{ secrets.SFTP_PASS }}
        run: |
          sshpass -p "$PASS" rsync -av \
            --delete \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='.gitattributes' \
            --exclude='.gitignore' \
            -e "ssh -o StrictHostKeyChecking=no -p 22" \
            ./  "$USER@$HOST:wilsonrlewis/zombie_game/"
